services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todoapp
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: todoapp
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: todo-client
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
